# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.0"

package:
  name: langchain-milvus
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-milvus/langchain_milvus-${{ version }}.tar.gz
  sha256: 5fd962874bd0fec1dfd87513610807fcf7abf8c1ec8a868819c0b02483c9708f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - langchain-core >=1.4.9,<2.0.0
    - pymilvus >=3.0.0,<4.0
    - milvus-lite >=3.1.0,<4.0

tests:
  - python:
      imports:
        - langchain_milvus
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/langchain-milvus/
  license: MIT
  license_file: LICENSE
  summary: An integration package connecting Milvus and LangChain
  repository: https://github.com/langchain-ai/langchain-milvus
  documentation: https://github.com/langchain-ai/langchain-milvus/tree/main/libs/milvus
  description: |
    LangChain Milvus provides integration between LangChain, a framework for
    building applications with large language models (LLMs), and Milvus, a
    vector database designed for similarity search and AI applications. It
    enables efficient vector storage and retrieval for use cases such as
    semantic search, recommendation systems, and Retrieval Augmented
    Generation (RAG).

extra:
  recipe-maintainers:
    - rxm7706
